- id: '1602180983675'
  alias: Новая автоматизация
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: dfd8b72669084285a631079842cad716
    entity_id: switch.konke_3afe170100510001_ebeabffe_on_off
    domain: switch
  condition: []
  action:
  - type: turn_on
    device_id: cba4509a096c11eb82b9f3ee34eaed5d
    entity_id: light.gateway_light_286c07f1c549
    domain: light
  mode: single
- id: '1602181419905'
  alias: Новая автоматизация 555
  description: ''
  trigger:
  - device_id: e4d8d299314844a580ab81d19556581c
    domain: zha
    platform: device
    type: device_shaken
    subtype: turn_on
  condition: []
  action:
  - service: light.turn_on
    data: {}
    entity_id: light.gateway_light_286c07f1c549
  mode: single
