resources:
  - url: /local/custom_ui/mini-media-player-bundle.js?v=0.9.8
    type: module
  - url: /local/custom_ui/monster-card.js
    type: js
  - url: /local/custom_ui/card-modder.js
    type: module
  - url: /local/custom_ui/card-tools.js
    type: js
  - url: /local/custom_ui/mini-graph-card-bundle.js
    type: module
  - url: /local/custom_ui/weather-card-mini.js
    type: js
  - url: /local/custom_ui/tracker-card.js?v=0
    type: js

name: OXOTH1Ks home
views:
  - title: Дом
    id: main
    theme: midnight
    icon: mdi:floor-plan
    cards:
      - type: custom:card-modder
        style:
          border-radius: 10px
        card:
          type: glance
          show_header_toggle: false
          title: Управление климатом
          entities:
            - climate.aeronik
            - climate.ariston
            - fan.xiaomi_miio_device
            - sensor.water_level
      - type: custom:card-modder
        style:
          border-radius: 10px
        card:
          type: glance
          show_header_toggle: false
          title: Безопасность
          entities:
            - binary_sensor.door_window_sensor_158d0001a9c200
            - lock.polycontrol_danalock_v3_btze_locked_2
      - type: custom:card-modder
        style:
          border-radius: 10px
        card:
          type: glance
          show_header_toggle: false
          title: Кухня
          entities:
            - light.gateway_light_286c07f1c549
            - binary_sensor.motion
            - sensor.illumination_286c07f1c549
            - switch.datchik_kukhnia
      - type: custom:card-modder
        style:
          border-radius: 10px
        card:          
          type: glance
          show_header_toggle: false
          title: Гостиная
          entities:
            - light.living_room
            - light.bathroom
            - sensor.temperature_158d00023764a1
            - sensor.humidity_158d00023764a1
            - sensor.pressure_158d00023764a1
            - switch.marantz_receiver
            - switch.plug_158d0001b195fd
            - group.heater_automation
#          - sensor.yandex_weather
      - type: custom:card-modder
        style:
          border-radius: 10px
        card:          
          type: glance
          show_header_toggle: false
          title: Ванная
          entities:
            - light.bathroom_wall
            - binary_sensor.motion_sensor_158d0001b177e8
            - binary_sensor.water_leak
      - type: custom:card-modder
        style:
          border-radius: 10px
        card:
          type: glance
          show_header_toggle: false
          title: Человеки
          entities:
            - device_tracker.iphone
            - device_tracker.iphone_2
      - type: custom:card-modder
        style:
          border-radius: 10px
        card:
          type: weather-forecast
          entity: weather.dark_sky
  - title: Медиа
    ip: media
    icon: mdi:play-box-outline
    cards:
      - type: custom:card-modder
        style:
          border-radius: 10px
        card:
          type: custom:mini-media-player
          entity: media_player.samsungtv
          icon: mdi:television
      - type: custom:card-modder
        style:
          border-radius: 10px
        card:
          type: custom:mini-media-player
          entity: media_player.mpd
          icon: mdi:television
      - type: custom:card-modder
        style:
          border-radius: 10px
        card:
          type: custom:mini-media-player
          entity: media_player.appletv
          icon: 'mdi:apple'
      - type: custom:card-modder
        style:
          border-radius: 10px
        card:
          type: entities
          show_header_toggle: false
          title: Радио
          entities:
            - script.play_pause_mpd
            - script.stop_mpd
            - script.maximum
            - script.nashe
            - script.ultra
            - script.volgogradfm
  - title: Сервер HA
    id: server
    icon: mdi:desktop-tower
    cards:
      - type: custom:card-modder
        style:
          border-radius: 10px
        card:
          type: entities
          show_header_toggle: false
          title: Ubuntu Server
          entities:
            - sensor.cpu_temperature
            - sensor.processor_use
            - sensor.memory_use_percent
            - sensor.disk_use_percent_home
            - sensor.last_boot
      - type: custom:card-modder
        style:
          border-radius: 10px
        card:
          type: entities
          title: Автоматизации
          entities:
            - automation.good_luck_notification
            - automation.notify_crazy_cat
            - automation.play_sound_people_at_home
            - automation.turn_on_bathroom_light
            - automation.turn_on_living_room_light_for_open_door
      - type: custom:card-modder
        style:
          border-radius: 10px
        card:
          type: entities
          show_header_toggle: false
          title: Состояние батарей датчиков
          entities:
            - sensor.door_sensor_battery_158d0001a9c200
            - sensor.motion_sensor_battery_158d0001b177e8
            - sensor.temperature_sensor_battery_158d00023764a1
            - sensor.button_sensor_battery_158d0001aaab2d
      - type: custom:card-modder
        style:
          border-radius: 10px
        card:
          type: entities
          title: Сцены
          show_header_toggle: false
          entities:
            - scene.livingroom_dim
            - scene.livingroom_normal
      - type: custom:card-modder
        style:
          border-radius: 10px
        card:
          type: entities
          show_header_toggle: false
          title: Интернет мониторинг
          entities:
            - sensor.internet_speed_in
            - sensor.internet_speed_out
            - sensor.wan_traffic_in_mean
            - sensor.wan_traffic_out_mean
        
  - title: Камеры
    id: cameras
    icon: mdi:cctv
    cards:
      - type: custom:card-modder
        style:
          border-radius: 10px
        card:
          type: picture-entity
          entity: camera.door
          aspect_ratio: 16:9
          camera_image: camera.door
          show_info: true
      - type: custom:card-modder
        style:
          border-radius: 10px
        card:          
          type: picture-entity
          entity: camera.kitchen
          aspect_ratio: 16:9
          camera_image: camera.kitchen
          show_info: true
      - type: custom:card-modder
        style:
          border-radius: 10px
        card:          
          type: picture-entity
          entity: camera.dacha
          aspect_ratio: 16:9
          camera_image: camera.dacha
          show_info: true
  - title: Графики
    id: graphs
    icon: mdi:chart-histogram
    cards:
      - type: custom:card-modder
        style:
          border-radius: 10px
        card:
          type: iframe
          url: !secret grafana_iframe
          aspect_ratio: 50%
      - type: custom:card-modder
        style:
          border-radius: 10px
        card:
          type: iframe
          url: !secret grafana_iframe2
          aspect_ratio: 50%
      - type: custom:card-modder
        style:
          border-radius: 10px
        card:
          type: iframe
          url: !secret grafana_iframe3
          aspect_ratio: 50%
  - title: Покупки
    id: shopping_list
    icon: mdi:cart
    cards:
      - type: custom:card-modder
        style:
          border-radius: 10px
        card:
          type: shopping-list
          title: Леруа
  - title: Климат
    icon: mdi:thermometer-lines
    cards:
    - type: vertical-stack
      cards:
       # Зал Температура
        - type: custom:card-modder
          style:
            border-radius: 10px
          card:
            type: custom:mini-graph-card
            entity: sensor.temperature_158d00023764a1
            detail: 1
            labels: true
            hours_to_show: 24
            height: 120
            line_color: '#EA811D'
            line_width: 6
            font_size: 120
            hide:
             - icon
 
          # Зал Влажность
        - type: custom:card-modder
          style:
            border-radius: 10px
          card:
            type: custom:mini-graph-card
            entity: sensor.humidity_158d00023764a1
            detail: 1
            labels: true
            hours_to_show: 24
            height: 120
            line_color: var(--primary-color)
            line_width: 6
            font_size: 120
            hide:
             - icon