

- alias: Проветрить днем
  trigger:
    - platform: time
      at: "10:00:00"
    - platform: time
      at: "12:00:00"
    - platform: time
      at: "14:00:00"
    - platform: time
      at: "16:00:00"
    - platform: time
      at: "18:00:00"
    - platform: time
      at: "19:00:00"
    - platform: time
      at: "20:00:00"
    - platform: time
      at: "21:00:00"
    - platform: time
      at: "22:00:00"
    - platform: time
      at: "23:00:00"
  action:
    - service: fan.turn_on
      target:
        entity_id: fan.pritochka

- alias: Выключить днем
  trigger:
    - platform: time
      at: "10:15:00"
    - platform: time
      at: "12:15:00"
    - platform: time
      at: "14:15:00"
    - platform: time
      at: "16:15:00"
    - platform: time
      at: "18:20:00"
    - platform: time
      at: "19:20:00"
    - platform: time
      at: "20:20:00"
    - platform: time
      at: "21:20:00"
    - platform: time
      at: "22:20:00"
    - platform: time
      at: "23:20:00"
  action:
    - service: fan.turn_off
      target:
        entity_id: fan.pritochka

- alias: Проветрить ночью
  trigger:
    - platform: time
      at: "00:00:00"
    - platform: time
      at: "01:00:00"
    - platform: time
      at: "02:00:00"
    - platform: time
      at: "03:00:00"
    - platform: time
      at: "04:00:00"
    - platform: time
      at: "05:00:00"
    - platform: time
      at: "06:00:00"
    - platform: time
      at: "07:00:00"
    - platform: time
      at: "08:00:00"
    - platform: time
      at: "09:00:00"
  action:
    - service: fan.turn_on
      target:
        entity_id: fan.pritochka

- alias: Выключить ночью
  trigger:
    - platform: time
      at: "00:15:00"
    - platform: time
      at: "01:15:00"
    - platform: time
      at: "02:15:00"
    - platform: time
      at: "03:15:00"
    - platform: time
      at: "04:15:00"
    - platform: time
      at: "05:15:00"
    - platform: time
      at: "06:15:00"
    - platform: time
      at: "07:15:00"
    - platform: time
      at: "08:15:00"
    - platform: time
      at: "09:15:00"
  action:
    - service: fan.turn_off
      target:
        entity_id: fan.pritochka

- alias: Увеличить скорость если жарко
  trigger:
    - platform: numeric_state
      entity_id: sensor.ble_temperature_a4c1382214a3
      above: 25
  condition:
    alias: "Процент между 1 и 10 приточка включена выключено отопление и на улице теплее 5 градусов и холоднее 25"
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: fan.pritochka
        attribute: percentage
        above: 1
        below: 10
      - condition: state
        entity_id: climate.living_room
        state: "off"
      - condition: state
        entity_id: fan.pritochka
        state: "on"
      - condition: numeric_state
        entity_id: weather.yandex_weather
        attribute: temperature
        above: 5
        below: 25
  action:
    - service: fan.increase_speed
      target:
        entity_id: fan.pritochka
      data: 
        percentage_step: 10

- alias: Увеличить еще скорость если жарко
  trigger:
    - platform: numeric_state
      entity_id: sensor.ble_temperature_a4c1382214a3
      above: 26
      below: 27
  condition:
    alias: "Процент между 11 и 20 приточка включена выключено отопление и на улице теплее 5 градусов и холоднее 25"
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: fan.pritochka
        attribute: percentage
        above: 11
        below: 20
      - condition: state
        entity_id: climate.living_room
        state: "off"
      - condition: state
        entity_id: fan.pritochka
        state: "on"
      - condition: numeric_state
        entity_id: weather.yandex_weather
        attribute: temperature
        above: 5
        below: 25
  action:
    - service: fan.increase_speed
      target:
        entity_id: fan.pritochka
      data: 
        percentage_step: 10

- alias: Уменьшить скорость если прохладно
  trigger:
    - platform: numeric_state
      entity_id: sensor.ble_temperature_a4c1382214a3
      below: 25
  condition:
    alias: "Процент между 10 и 20 приточка включена выключено отопление и на улице теплее 5 градусов и холоднее 25"
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: fan.pritochka
        attribute: percentage
        above: 10
        below: 20
      - condition: state
        entity_id: climate.living_room
        state: "off"
      - condition: state
        entity_id: fan.pritochka
        state: "on"
      - condition: numeric_state
        entity_id: weather.yandex_weather
        attribute: temperature
        above: 5
        below: 25
  action: 
    - service: fan.decrease_speed
      target:
        entity_id: fan.pritochka
      data: 
        percentage_step: 10

- alias: Уменьшить еще скорость если прохладно
  trigger:
    - platform: numeric_state
      entity_id: sensor.ble_temperature_a4c1382214a3
      below: 25
  condition:
    alias: "Процент между 20 и 30 приточка включена выключено отопление и на улице теплее 5 градусов и холоднее 25"
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: fan.pritochka
        attribute: percentage
        above: 20
        below: 30
      - condition: state
        entity_id: climate.living_room
        state: "off"
      - condition: state
        entity_id: fan.pritochka
        state: "on"
      - condition: numeric_state
        entity_id: weather.yandex_weather
        attribute: temperature
        above: 5
        below: 25
  action: 
    - service: fan.decrease_speed
      target:
        entity_id: fan.pritochka
      data: 
        percentage_step: 10
        