- alias: Select favorite speed by slider
  trigger:
    platform: state
    entity_id: input_number.xiaomi_fresh_air_ventilator_favorite_speed
  action:
    - service: xiaomi_miio_airpurifier.fan_set_favorite_speed
      data_template:
        entity_id: fan.pritochka
        speed: "{{ states.input_number.xiaomi_fresh_air_ventilator_favorite_speed.state|int }}"

- alias: Monitor favorite speed and update slider
  trigger:
    platform: state
    entity_id: sensor.xiaomi_fresh_air_ventilator_favorite_speed
  action:
    - service: input_number.set_value
      entity_id: input_number.xiaomi_fresh_air_ventilator_favorite_speed
      data_template:
        value: "{{ states.fan.pritochka.attributes.favorite_speed }}"

- alias: Проветрить днем
  trigger:
    - platform: time
      at: "10:00:00"
    - platform: time
      at: "12:00:00"
    - platform: time
      at: "14:00:00"
    - platform: time
      at: "16:00:00"
    - platform: time
      at: "18:00:00"
  action:
    - service: fan.turn_on
      target:
        entity_id: fan.pritochka

- alias: Выключить днем
  trigger:
    - platform: time
      at: "10:30:00"
    - platform: time
      at: "12:30:00"
    - platform: time
      at: "14:30:00"
    - platform: time
      at: "16:30:00"
    - platform: time
      at: "18:30:00"
  action:
    - service: fan.turn_off
      target:
        entity_id: fan.pritochka

- alias: Проветрить ночью
  trigger:
    - platform: time
      at: "00:00:00"
    - platform: time
      at: "01:00:00"
    - platform: time
      at: "02:00:00"
    - platform: time
      at: "03:00:00"
    - platform: time
      at: "04:00:00"
    - platform: time
      at: "05:00:00"
    - platform: time
      at: "06:00:00"
    - platform: time
      at: "07:00:00"
    - platform: time
      at: "08:00:00"
    - platform: time
      at: "09:00:00"
  action:
    - service: fan.turn_on
      target:
        entity_id: fan.pritochka

- alias: Выключить ночью
  trigger:
    - platform: time
      at: "00:10:00"
    - platform: time
      at: "01:10:00"
    - platform: time
      at: "02:10:00"
    - platform: time
      at: "03:10:00"
    - platform: time
      at: "04:10:00"
    - platform: time
      at: "05:10:00"
    - platform: time
      at: "06:10:00"
    - platform: time
      at: "07:10:00"
    - platform: time
      at: "08:10:00"
    - platform: time
      at: "09:10:00"
  action:
    - service: fan.turn_off
      target:
        entity_id: fan.pritochka
