# Включение света в ванной днем
- alias: Turn on bathroom light on day
  trigger:
    platform: state
    entity_id: binary_sensor.vannaia
    to: "on"
  condition:
    condition: time
    after: "07:00:00"
    before: "23:30:00"
  action:
    service: light.turn_on
    entity_id: light.vannaia

# Выключение света в ванной без движения
- alias: Turn off bathroom light
  trigger:
    - platform: state
      entity_id: binary_sensor.vannaia
      to: "off"
  #  condition:
  #    - condition: state
  #      entity_id: binary_sensor.0x086bd7fffee96c2a_contact
  #      state: "on"
  action:
    service: light.turn_off
    entity_id:
      - light.vannaia


- alias: Turn on hall light day
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_motion_wirenboard
    to: "on"
  condition:
    condition: sun
    after: sunset
    after_offset: "-00:30:00"
  action:
    service: light.turn_on
    target:
      entity_id: light.koridor
    data:
      brightness: 255


- alias: Turn on hall light night
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_motion_wirenboard
    to: "on"
  condition:
    condition: sun
    before: sunrise
    after_offset: "-00:30:00"
  action:
    - service: light.turn_on
      target:
        entity_id: light.koridor
      data:
        brightness: 1
    - service: light.turn_on
      entity_id: light.nochnik

- alias: Turn on kitchen light
  trigger:
    platform: state
    entity_id: binary_sensor.rabochaia_zona
    to: "on"
  condition:
    condition: or
    conditions:
      - condition: sun
        before: sunrise
        after_offset: "-00:30:00"
      - condition: sun
        after: sunset
        after_offset: "-00:30:00"
  action:
    service: light.turn_on
    entity_id: light.podsvetka


- alias: Turn off dining room light
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_motion_wirenboard
    to: "off"
  condition:
    condition: sun
    before: sunrise
    after_offset: "-00:30:00"
  action:
    - service: light.turn_off
      target:
        entity_id: light.nochnik
    - service: light.turn_off
      target:
        entity_id: light.koridor

- alias: Turn off hall light
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_motion_wirenboard
    to: "off"
  action:
    service: light.turn_off
    entity_id: light.koridor
#Управление светильниками с пульта
- alias: Turn on dining room and kitchen light
  trigger:
    platform: state
    entity_id: binary_sensor.ble_remote_binary_single_press_f82441ed080f
    to: "on"
  action:
    - service: light.turn_on
      entity_id: light.yeelight_ceilb_0x182d2cc2
    - service: light.turn_on
      entity_id: light.yeelight_ceila_0x184309e8

- alias: Turn off dining room and kitchen light
  trigger:
    platform: state
    entity_id: binary_sensor.ble_remote_binary_single_press_f82441ed080f
    to: "off"
  action:
    - service: light.turn_off
      entity_id: light.yeelight_ceilb_0x182d2cc2
    - service: light.turn_off
      entity_id: light.yeelight_ceila_0x184309e8

- alias: Dimm on dining room and kitchen light
  trigger:
    platform: state
    entity_id: sensor.ble_remote_f82441ed080f
  condition:
    condition: state
    entity_id: sensor.ble_remote_f82441ed080f
    state: "single press +"
  action:
    - service: light.turn_on
      data:
        entity_id: light.yeelight_ceilb_0x182d2cc2
        brightness_step_pct: 20
    - service: light.turn_on
      data:
        entity_id: light.yeelight_ceila_0x184309e8
        brightness_step_pct: 20

- alias: Dimm on dining room and kitchen light
  trigger:
    platform: state
    entity_id: sensor.ble_remote_f82441ed080f
  condition:
    condition: state
    entity_id: sensor.ble_remote_f82441ed080f
    state: "single press -"
  action:
    - service: light.turn_on
      data:
        entity_id: light.yeelight_ceilb_0x182d2cc2
        brightness_step_pct: -20
    - service: light.turn_on
      data:
        entity_id: light.yeelight_ceila_0x184309e8
        brightness_step_pct: -20

- alias: Turn on dining room and kitchen night light
  trigger:
    platform: state
    entity_id: sensor.ble_remote_f82441ed080f
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.ble_remote_f82441ed080f
        state: "single press m"
      - condition: state
        entity_id: light.yeelight_ceilb_0x182d2cc2_nightlight
        state: "off"
  action:
    - service: light.turn_on
      entity_id: light.yeelight_ceilb_0x182d2cc2_nightlight
    - service: light.turn_on
      entity_id: light.yeelight_ceila_0x184309e8_nightlight

- alias: Turn off dining room and kitchen night light
  trigger:
    platform: state
    entity_id: sensor.ble_remote_f82441ed080f
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.ble_remote_f82441ed080f
        state: "single press m"
      - condition: state
        entity_id: light.yeelight_ceilb_0x182d2cc2_nightlight
        state: "on"
  action:
    - service: light.turn_on
      entity_id: light.yeelight_ceilb_0x182d2cc2
    - service: light.turn_on
      entity_id: light.yeelight_ceila_0x184309e8
